import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import LoginBtn from "@/component/LoginBtn";
import LogoutBtn from "@/component/LogoutBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let userInfo = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div className="flex flex-row gap-4 navbar">
            <div>
              <Link href="/">
                <h2>main 페이지</h2>
              </Link>
            </div>
            <div>
              <Link href="/list">
                <h2>list 페이지</h2>
              </Link>
            </div>
            <div>
              <Link href="/write">
                <h2>글작성 페이지</h2>
              </Link>
            </div>
            <div>
              <Link href="/sign">
                <h2>회원가입 페이지</h2>
              </Link>
            </div>
            <div>
              {userInfo ? (
                <>
                  <span>{userInfo.user.name}</span>
                  <LogoutBtn />
                </>
              ) : (
                <LoginBtn />
              )}
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
