import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import LoginBtn from "@/component/LoginBtn";
import LogoutBtn from "@/component/LogoutBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { cookies } from "next/headers";
import DarkMode from "./DarkMode";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ! localStorage
// "use client";

// function 컴포넌트() {
//   useEffect(() => {
//     if (typeof window != "undefined") {
//       let res = localStorage.setItem("이름", "kim");
//     }
//   }, []);

//   return 생략;
// }

// ! cookies
//import { cookies } from "next/headers";

// export default function 서버컴포넌트(){

// }

// 2. cookie에 따라서 UI가 어떻게 변할지 작성
export default async function RootLayout({ children }) {
  let userInfo = await getServerSession(authOptions);

  let res = cookies().get("mode");
  console.log(res);

  return (
    <html lang="en">
      <body
        className={res !== undefined && res.value === "dark" ? "dark-mode" : ""}
      >
        <header>
          <div className="flex flex-row gap-4 navbar">
            <div>
              <Link href="/">
                <h2>main 페이지</h2>
              </Link>
            </div>
            <div>
              <Link href="/list">
                <h2>list 페이지</h2>
              </Link>
            </div>
            <div>
              <Link href="/write">
                <h2>글작성 페이지</h2>
              </Link>
            </div>
            <div>
              <Link href="/register">
                <h2>회원가입 페이지</h2>
              </Link>
            </div>
            <div>
              <DarkMode mode={res.value} />
            </div>
            <div>
              {userInfo ? (
                <>
                  <span>{userInfo.user.name}</span>
                  <LogoutBtn />
                </>
              ) : (
                <LoginBtn />
              )}
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
